export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const SET_COLLECTIONS = 'SET_COLLECTIONS';
export const GET_COLLECTIONS_FAILED = 'GET_COLLECTIONS_FAILED';